development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  domain: example.com
  mailer: Example <noreply@example.com>
  session_key: eldorado_development
  secret: YrDOFOmYJyFg2tTZykCbZjWYQUbKBt

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  domain: example.com
  mailer: Example <noreply@example.com>
  session_key: eldorado_test
  secret: Pl8qJNFc8mo1yt1xtHOmfUGHOPEutu

production:
  adapter: mysql
  database: eldorado_production
  username: root
  password: 
  host: localhost
  domain: 
  mailer: 
  session_key: 
  secret: 
