development:
  address: smtp.gmail.com
  port: 587
  user_name: user@domain.com
  password: password
  
test:
  address: smtp.gmail.com
  port: 587
  user_name: user@domain.com
  password: password
    
production:
  address: smtp.gmail.com
  port: 587
  user_name: user@domain.com
  password: password

# Move this to config/environment.rb if using these SMTP settings...
# require 'tlsmail'
# smtp = YAML.load_file('config/smtp.yml')
# Net::SMTP.enable_tls(OpenSSL::SSL::VERIFY_NONE)
# ActionMailer::Base.default_url_options[:host] = smtp[RAILS_ENV]['domain']
# ActionMailer::Base.smtp_settings = {
#   :address => smtp[RAILS_ENV]['address'],
#   :port => smtp[RAILS_ENV]['port'],
#   :domain => smtp[RAILS_ENV]['domain'],
#   :authentication => :plain,
#   :user_name => smtp[RAILS_ENV]['user_name'],
#   :password => smtp[RAILS_ENV]['password']
# }
# 
# MAILER = smtp[RAILS_ENV]['mailer']
